#!/bin/bash

#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
#
# Copyright (C) 2015-2022 Ed Jorgensen
#

# Create and assemble the link script file, as described in Chapter 5,
# Tool Chain. Use the script to assemble and link the program.
# Ensure that the script correctly assembles and links.

# Simple assemble/link script.
if [ -z $1 ]; then 
    echo "Usage:  ./asm64 <asmMainFile> (no extension)" 
    exit
fi 

# Verify no extensions were entered 
if [ ! -e "$1.asm" ]; then 
    echo "Error, $1.asm not found." 
    echo "Note, do not enter file extensions." 
    exit 
fi 

# Compile, assemble, and link. 
yasm -Worphan-labels -g dwarf2 -f elf64 $1.asm -l $1.lst 
ld -g -o $1.out $1.o

